const path = require( 'path' );
// setup project root path
const projectRoot = path.dirname( path.dirname( __dirname ) );
const host = require( `${ projectRoot }/settings/server/config` ).host;
const browserlist = require( `${ projectRoot }/settings/browserlist/config` );

module.exports = {
    js: {
        frontend: {
            src: [
                `${ projectRoot }/static/src/js/**/*.js`,
            ],
            lint: {
                rule: `${ projectRoot }/settings/lint/eslint/frontend.js`,
                ignoreFile: `${ projectRoot }/settings/lint/eslint/.frontend_ignore`,
            },
        },
        backend: {
            src: [
                `${ projectRoot }/**/*.js`,
            ],
            lint: {
                rule: `${ projectRoot }/settings/lint/eslint/backend.js`,
                ignoreFile: `${ projectRoot }/settings/lint/eslint/.backend_ignore`,
            },
        },
    },
    sass: {
        src: [
            `${ projectRoot }/static/src/sass/**/*.scss`,
        ],
        dest: `${ projectRoot }/static/dist/css`,
        static: {
            fileName: '_static.scss',
            data:
                `// this file is automatically generated\n` +
                `// don't change anthing because it will be overwrite next time\n` +
                `// change file content at ${ __dirname }/config.js\n` +
                `$staticRoot: '${ host }';\n` +
                `$font: '#{ $staticRoot }/font';\n` +
                `$image: '#{ $staticRoot }/image';\n`,
            dest: `${ projectRoot }/static/src/sass/components/common`,
        },
    },
    pug: {
        src: [
            `${ projectRoot }/views/**/*.pug`,
        ],
    },
    browserlist,
    sourcemaps: {
        dest: '.',
    }
};
